# New ports collection makefile for:	rubygems-algorithms
# Date created:		2011-07-23
# Whom:			Jonathan Walker <kallous@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	algorithms
PORTVERSION=	0.3.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	kallous@gmail.com
COMMENT=	A library of algorithms and containers.

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
