# New ports collection makefile for:	rubygem-logger
# Date created:		2011-07-23
# Whom:			Jonathan Walker <kallous@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	logger
PORTVERSION=	1.2.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	kallous@gmail.com
COMMENT=	simple logging utility

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
