# New ports collection makefile for:	rubygems-dnsruby
# Date created:		2011-07-23
# Whom:			Jonathan Walker <kallous@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	dnsruby
PORTVERSION=	1.52
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	kallous@gmail.com
COMMENT=	Ruby DNS(SEC) implementation

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
